### ISSUE TITLE
[Bug]: Wayland Team Agent Coordination - Claude Code ACP Backend Crashes

### ISSUE THREAD

**Issue by dariobros** [FerroxLabs/wayland#330]
### Platform

macOS (Apple Silicon)

### Wayland Version

**Version:** Wayland v0.11.3 (production)

## Bug Report: Wayland Team Agent Coordination - Claude Code ACP Backend Crashes

**Version:** Wayland v0.11.3 (production)
**OS:** macOS 25.4.0 (arm64)
**Electron:** 41.6.0
**Node:** v24.15.0 (built-in), v25.5.0 (system)

### Expected Behavior
Spawning a `coder` agent with `backend: claude` should start a Claude Code ACP session that can receive tasks and return results.

### Actual Behavior

Assessment: Where the Problem Lies
This is a Wayland app bug, not an external setup issue. The failures are in Wayland's bundled dependencies and ACP protocol implementation:

Bundled @agentclientprotocol/sdk has broken zod/v4 import — This is inside Wayland's app.asar, not user-configurable
ACP session/set_mode handler missing "default" mode — Protocol implementation bug
MCP server readiness race condition — Team coordination infrastructure issue
No fallback when primary backend fails — System keeps retrying same broken backend

Claude Code ACP agent crashes immediately on startup with:
error: Cannot find module 'zod/v4' from '.../claude-agent-acp@0.51.0/node_modules/@agentclientprotocol/sdk/dist/schema/zod.gen.js'
Followed by repeated `session/set_mode` failures for "default" mode across all backends.

### Steps to Reproduce
1. Start Wayland
2. Create a team with `team_spawn_agent` using `agent_type: "claude"` 
3. Assign a task via `team_task_create` + `team_send_message`
4. Observe agent crash in logs, task never completes

### Log Evidence
- `2026-06-25.log` lines 594-610, 617-632, 638-655, 661-678, 737-755, 778-795, 801-818, 855-872, 878-895, 901-916, 922-939, 974-992, 1015-1032, 1038-1055, 1110-1128
- Multiple `AgentStartupError: Agent exited before initialize completed (code: 1)`
- Repeated `Invalid params: mode not found: default` for `session/set_mode`

### Affected Backends
- `claude` (all models: sonnet, haiku, default, opus[1m]) — **100% failure**
- `opencode` — starts but crashes with mode errors
- `gemini` — API access error for configured models
- `codex` — works but has stdin lifecycle issues

### Workaround Used
Synthesized debate results manually (Round 3) since agents couldn't complete Round 2 cross-examination.

### Priority
**P0 — Blocks all multi-agent workflows using Claude Code backend**

### Suggested Fixes
1. Fix `@agentclientprotocol/sdk` bundled dependency (zod/v4 resolution)
2. Register "default" mode in ACP `session/set_mode` handler for all backends
3. Add backend health check + automatic fallback (e.g., claude → opencode → codex)
4. Increase MCP readiness timeout or add retry logic

### Steps to Reproduce

1. Start Wayland v0.11.3 on macOS
2. Create a team using team coordination tools
3. Spawn a coder agent with agent_type: "claude" (any model: sonnet, haiku, default, opus[1m])
4. Create a task with team_task_create and assign to the coder agent
5. Send a message to the agent with team_send_message
6. Observe agent crashes in logs, task never completes

### Expected Behavior

Claude Code ACP agent starts successfully, receives the task, processes it, and returns results. The agent should remain stable for the duration of the task.

### Actual Behavior

Claude Code ACP agent crashes immediately on startup with:
error: Cannot find module 'zod/v4' from '/private/var/folders/.../claude-agent-acp@0.51.0/node_modules/@agentclientprotocol/sdk/dist/schema/zod.gen.js'
AgentStartupError: Agent exited before initialize completed (code: 1)

Repeated session/set_mode failures across all backends:

Invalid params: mode not found: default

MCP readiness timeouts (60s):
Timed out waiting for MCP ready: slot-XXXXX
Agents repeatedly crash with SIGTERM, tasks never complete. Only Codex (gpt-oss-120b) agents work intermittently.

**Comment by FerroxLabs** [comment]
Core-lane verdict: not in the Rust engine. The reported failures are in the desktop app's bundled Node/TypeScript ACP SDK: "Cannot find module 'zod/v4'" is a broken bundled dependency inside app.asar, and "Invalid params: mode not found: default" is the desktop ACP session handler missing the default mode. The wayland-core ACP bridge (crates/wcore-acp/ + crates/wcore-cli/src/acp_engine.rs) implements the TurnEngine relay + approval lifecycle correctly and does not emit these errors. Bouncing to the desktop lane (flagged needs:overwatch). If Overwatch suspects the "mode not found" originates engine-side, point me at an engine repro and I'll re-open the core investigation.

**Comment by FerroxLabs** [comment]
**Overwatch ruling — #330. Core verdict accepted: not in the Rust engine.** It is the desktop bundled Node ACP SDK: "Cannot find module 'zod/v4'" (broken bundled dep in app.asar) + "Invalid params: mode not found: default" (desktop ACP session handler missing the default mode). Route to **desktop (needs:desktop)**. Note: the zod/v4 failure is the SAME class as #373 (corrupt bunx agent cache, incomplete zod extraction) — bundle #330 + #373 as one zod-bundling/ACP-startup fix in BH2's lane.

**Comment by FerroxLabs** [comment]
The primary crash here (broken bundled ACP dependency, Cannot find module zod/v4) is self-healed in Wayland 0.11.7 (PR #429). Shipping now via auto-update. If the Claude Code ACP backend still crashes on 0.11.7, reopen with the new logs and we'll chase the residual. Closing as released.

**Comment by dariobros** [comment]
Confirmed working on 0.11.7. Used aion_create_team to spawn a Claude Code 
developer agent, assigned a Python task — agent started cleanly, wrote and 
ran hello_world.py successfully. No zod/v4 crash, no mode errors. Fixed.

<img width="1423" height="907" alt="Image" src="https://github.com/user-attachments/assets/4bb137b9-974e-459d-b241-c6f32ebe0536" />
